language: node_js

node_js:
    - 0.12.9
    - 4.2.4
    - 5.4.1

os:
    - linux
    - osx

notifications:
  email:
    - rod@vagg.org

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.9
            - g++-4.9

before_install:
    - export CC="gcc-4.9" CXX="g++-4.9"
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install nvm     ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source ~/.nvm/nvm.sh ; fi

before_script:
    - npm install -g mocha

script:
    - npm test
